---
- name: Reboot (Debian/Ubuntu)
  ansible.builtin.reboot:
    reboot_timeout: 300
  poll: 0
  register: reboot_result
  when: ansible_os_family == "Debian" and ansible_os_family == "Ubuntu"

- name: Reboot (RedHat/CentOS/Fedora)
  ansible.builtin.reboot:
    reboot_timeout: 300
  poll: 0
  register: reboot_result
  when: ansible_os_family == "RedHat"

- name: Reboot (Suse)
  ansible.builtin.reboot:
    reboot_timeout: 300
  poll: 0
  register: reboot_result
  when: ansible_os_family == "Suse"

- name: Reboot (Archlinux)
  ansible.builtin.reboot:
    reboot_timeout: 300
  poll: 0
  register: reboot_result
  when: ansible_os_family == "Archlinux"

- name: Wait for reboot to complete
  ansible.builtin.wait_for_connection:
    timeout: 300
  when: reboot_result is defined 
