---
- name: "Hosts configure, update and install packages"
  hosts: "nodes"
  gather_facts: true 
  become: true
  vars_files:
    - "../../vars/values.yml"
  tasks:
    - include_tasks: "modules/update.yml"
    - include_tasks: "modules/reboot.yml"

    
  