---
- name: "Hosts configure, update and install packages"
  hosts: "nodes"
  gather_facts: true
  become: true
  vars_files:
    - "../../vars/values.yml"
  tasks:
    - name: Add ansible user
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: "/bin/bash"
        create_home: yes

    - name: Set authorized key for ansible user
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ ansible_public_key }}"

    - name: Add ansible user to sudoers (create directory if needed)
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Add ansible user to sudoers
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        owner: root
        group: root
        mode: "0440"
        content: |
          # User privileges for ansible IaC automation
          {{ ansible_user }} ALL=(ALL) NOPASSWD: ALL
        validate: "visudo -cf %s"
